name = "public-bucket"
main = "index.js"
compatibility_date = "2022-07-12"
workers_dev = true
account_id = "9fbfc5a598619165478af4be82890d28"

[[r2_buckets]]
binding = "PUBLIC_BUCKET"
bucket_name = "pkoch-public"
preview_bucket_name =  "pkoch-public"

[[kv_namespaces]]
binding = "SHORT_LINKS"
id = "placeholder"
preview_id = "placeholder"

[vars]
JWKS_URL = "https://example.com/.well-known/jwks.json"
JWT_ISSUER = "https://example.com/"
JWT_AUDIENCE = "public-bucket"
